{{- if .Values.imagePullSecret.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edc-dataplane.fullname" . }}-imagepullsecret
  labels:
    {{- include "edc-dataplane.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- end }}
