auth:
  #jwksUrl: "http://192.168.205.1:8081/auth/realms/catenax/protocol/openid-connect/certs"
  jwksUrl: "http://catenax-keycloak.managed-identity-wallets/realms/catenax/protocol/openid-connect/certs"
  #issuerUrl: "http://192.168.205.1:8081/auth/realms/catenax"
  issuerUrl: "http://catenax-keycloak.managed-identity-wallets/realms/catenax"
  redirectUrl: "http://localhost:8080/callback"
  realm: "catenax"
  roleMappings: "create_wallets:add_wallets,view_wallets:view_wallets,update_wallets:update_wallets,delete_wallets:delete_wallets,view_wallet:view_wallet,update_wallet:update_wallet"
  resourceId: "ManagedIdentityWallets"
datapool:
  url: "https://catenax-bpdm-dev.demo.catena-x.net"
  authUrl: "https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
revocation:
  refreshHour: "3"
  revocationServiceUrl: http://localhost:8086
acapy:
  logLevel: "DEBUG"
  ledgerUrl: "http://dev.greenlight.bcovrin.vonx.io"
  endpointPort: "8000"
  endpointUrl: "https://managed-identity-wallets.dev.demo.catena-x.net:8000/"
  adminPort: "11000"
  adminUrl: "http://localhost:11000"
  imageName: "bcgovimages/aries-cloudagent"
  tag: "py36-1.16-1_0.7.4"
certificate:
  host: "managed-identity-wallets.local.demo.catena-x.net"
image:
  name: "catena-x/managed-identity-wallets"
postgresql:
  enabled: true
isLocal: true