---
dataplane:
  image:
    tag: latest
    pullPolicy: Always
  ingresses:
    - hostname: "sokrates.int.catena-x.net"
  env:
    EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT: "http://sokrates-controlplane:8182/validation/token"
    EDC_VAULT_HASHICORP_URL: https://vault.demo.catena-x.net
    EDC_VAULT_HASHICORP_API_SECRET_PATH: /v1/edc

controlplane:
  enabled: true
  image:
    tag: latest
    pullPolicy: Always
  ingresses:
    - hostname: "sokrates.int.catena-x.net"
  env:
    EDC_OAUTH_CLIENT_ID: dev-sokrates-EDC_OAUTH_CLIENT_ID
    EDC_OAUTH_PRIVATE_KEY_ALIAS: dev-sokrates-EDC_OAUTH_PRIVATE_KEY_ALIAS
    EDC_OAUTH_PUBLIC_KEY_ALIAS: dev-sokrates-EDC_OAUTH_PUBLIC_KEY_ALIAS
    IDS_WEBHOOK_ADDRESS: "https://sokrates.int.catena-x.net/api/v1/ids"
    EDC_IDS_ENDPOINT: "https://sokrates.int.catena-x.net/api/v1/ids"
    EDC_IDS_DESCRIPTION: "sokrates EDC Control Plane"
    EDC_DATASOURCE_ASSET_URL: &psqlJdbcUrl "jdbc:postgresql://sokrates-postgres:5432/edc"
    EDC_DATASOURCE_CONTRACTDEFINITION_URL: *psqlJdbcUrl
    EDC_DATASOURCE_CONTRACTNEGOTIATION_URL: *psqlJdbcUrl
    EDC_DATASOURCE_POLICY_URL: *psqlJdbcUrl
    EDC_DATASOURCE_TRANSFERPROCESS_URL: *psqlJdbcUrl
    EDC_DATAPLANE_SELECTOR_HTTPPROXY_URL: http://sokrates-dataplane:9999/api/dataplane/control
    EDC_DATAPLANE_SELECTOR_HTTPPROXY_PROPERTIES: >-
      {
        "publicApiUrl": "https://sokrates.int.catena-x.net/dataplane/api/public"
      }
    EDC_TRANSFER_PROXY_ENDPOINT: http://sokrates-dataplane:8185/dataplane/api/public
    EDC_TRANSFER_PROXY_TOKEN_SIGNER_PRIVATEKEY_ALIAS: dev-sokrates-EDC_TRANSFER_PROXY_TOKEN_SIGNER_PRIVATEKEY_ALIAS
    EDC_TRANSFER_PROXY_TOKEN_VERIFIER_PUBLICKEY_ALIAS: dev-sokrates-EDC_TRANSFER_PROXY_TOKEN_VERIFIER_PUBLICKEY_ALIAS
    EDC_VAULT_HASHICORP_URL: https://vault.demo.catena-x.net
    EDC_VAULT_HASHICORP_API_SECRET_PATH: /v1/edc
