#################################################################################
#  Copyright (c) 2023 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#################################################################################


fullnameOverride: tx-prod
################################
# EDC ControlPlane + DataPlane #
################################
participant:
  id: "test-participant"
  contextId: "test-participant-context"
iatp:
  # Decentralized IDentifier
  id: "did:web:changeme"
  sts:
    dim:
      url: "https://somewhere.dim.org"
    oauth:
      token_url: "https://changeme.org"
      client:
        id: "test-client-id"
        secret_alias: "test-alias"
controlplane:
  debug:
    enabled: true
    port: 1044
    suspendOnStart: false
  service:
    type: NodePort
  endpoints:
    management:
      authKey: password
  image:
    pullPolicy: Never
    tag: "latest"
    repository: "edc-controlplane-postgresql-hashicorp-vault"
  securityContext:
    # avoids some errors in the log: cannot write temp files of large multipart requests when R/O
    readOnlyRootFilesystem: false
  bdrs:
    server:
      url: "https://bdrs.test.org"
dataplane:
  debug:
    enabled: true
    port: 1045
    suspendOnStart: false
  endpoints:
    proxy:
      authKey: password
  image:
    pullPolicy: Never
    tag: "latest"
    repository: "edc-dataplane-hashicorp-vault"
  securityContext:
    # avoids some errors in the log: cannot write temp files of large multipart requests when R/O
    readOnlyRootFilesystem: false
  aws:
    endpointOverride: http://minio:9000
    secretAccessKey: qwerty123
    accessKeyId: qwerty123
  token:
    signer:
      privatekey_alias: "key-1"
    verifier:
      publickey_alias: "key-1"
postgresql:
  image:
    repository: "bitnamilegacy/postgresql"
    tag: "16.2.0-debian-12-r10"
  jdbcUrl: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/edc
  auth:
    username: user
    password: password
vault:
  hashicorp:
    url: http://{{ .Release.Name }}-vault:8200
    token: root

  # the post-start object is still needed for the upgradeability test
  # todo: remove this after 0.7.0 is released
  server:
    postStart:
      - sh
      - -c
      - |-
        {
        sleep 5

        /bin/vault kv put secret/client-secret content=kEmH7QRPWhKfy8f+x0pFMw==

        /bin/vault kv put secret/aes-keys content=YWVzX2VuY2tleV90ZXN0Cg==
        }
tests:
  hookDeletePolicy: before-hook-creation
