#
#  Copyright (c) 2023 ZF Friedrichshafen AG
#  Copyright (c) 2023 Mercedes-Benz Tech Innovation GmbH
#  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#  Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#

{{- $fullName := include "edc-dataplane.fullname" . }}
{{- $labels := include "edc-dataplane.labels" . | nindent 4 }}
{{- $gitVersion := .Capabilities.KubeVersion.GitVersion }}
{{- $edcEndpoints := .Values.edc.endpoints }}
{{- $namespace := .Release.Namespace }}
{{- range .Values.ingresses }}
{{- if and .enabled .endpoints }}
{{- $ingressName := printf "%s-%s" $fullName .hostname }}
---
{{- if semverCompare ">=1.19-0" $gitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $gitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $ingressName }}
  namespace: {{ $namespace | default "default" | quote }}
  labels:
    {{- $labels | nindent 2 }}
  annotations:
    {{- if and .className (not (semverCompare ">=1.18-0" $gitVersion)) }}
    {{- if not (hasKey .annotations "kubernetes.io/ingress.class") }}
    {{- $_ := set .annotations "kubernetes.io/ingress.class" .className}}
    {{- end }}
    {{- end }}
    {{- if .certManager }}
    {{- if .certManager.issuer }}
    {{- $_ := set .annotations "cert-manager.io/issuer" .certManager.issuer}}
    {{- end }}
    {{- if .certManager.clusterIssuer }}
    {{- $_ := set .annotations "cert-manager.io/cluster-issuer" .certManager.clusterIssuer}}
    {{- end }}
    {{- end }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .className (semverCompare ">=1.18-0" $gitVersion) }}
  ingressClassName: {{ .className }}
  {{- end }}
  {{- if .hostname }}
  {{- if .tls.enabled }}
  tls:
    - hosts:
        - {{ .hostname }}
      {{- if .tls.secretName }}
      secretName: {{ .tls.secretName }}
      {{- else }}
      secretName: {{ $ingressName }}-tls
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .hostname }}
      http:
        paths:
          {{- $ingressEdcEndpoints := .endpoints }}
          {{- range  $name, $mapping := $edcEndpoints }}
          {{- if (has $name $ingressEdcEndpoints) }}
          - path: {{ $mapping.path }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $gitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $mapping.port }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $mapping.port }}
              {{- end }}
        {{- end }}
  {{- end }}
  {{- end }}
{{- end }}{{- /* end: if .enabled */}}
{{- end }}{{- /* end: range .Values.ingresses */}}
