---
apiVersion: v2
name: edc-controlplane
description: >-
  EDC Control-Plane - The Eclipse DataSpaceConnector administration layer with responsibility of resource management and govern contracts and data transfers
home: https://github.com/catenax-ng/product-edc/charts/edc-controlplane
type: application
appVersion: "0.1.5"
version: 0.1.5
maintainers: []
