---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "txdc.fullname" . }}-dataplane
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "txdc.dataplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dataplane.service.type }}
  ports:
    - port: {{ .Values.dataplane.endpoints.default.port }}
      targetPort: default
      protocol: TCP
      name: default
    - port: {{ .Values.dataplane.endpoints.control.port }}
      targetPort: control
      protocol: TCP
      name: control
    - port: {{ .Values.dataplane.endpoints.public.port }}
      targetPort: public
      protocol: TCP
      name: public
    - port: {{ .Values.dataplane.endpoints.observability.port }}
      targetPort: observability
      protocol: TCP
      name: observability
    - port: {{ .Values.dataplane.endpoints.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "txdc.dataplane.selectorLabels" . | nindent 4 }}
