---
name: "Lint helm charts"

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - '**'
      - '!charts/**'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**'
      - '!charts/**'

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
    ##############
    ### Set-Up ###
    ##############
    -
      name: Checkout
      uses: actions/checkout@v3.2.0
      with:
        fetch-depth: 0
    -
      name: helm (setup)
      uses: azure/setup-helm@v3.4
      with:
        version: v3.8.1
    -
      name: python (setup)
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    -
      name: chart-testing (setup)
      uses: helm/chart-testing-action@v2.3.1
    #####################
    ### Chart Testing ###
    #####################
    -
      name: chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --config ct.yaml --target-branch develop)
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi
    -
      name: chart-testing (lint)
      if: steps.list-changed.outputs.changed == 'true'
      run: |
        ct lint \
          --config ct.yaml \
          --all
