#
#  Copyright (c) 2023 Mercedes-Benz Tech Innovation GmbH
#  Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#

---
name: "Publish OpenAPI to Swaggerhub"

on:
  workflow_call:
    inputs:
      downstream-version:
        required: false
        type: string
      upstream-version:
        required: false
        type: string

  workflow_dispatch:
    inputs:
      downstream-version:
        required: false
        description: "Version of the Tractus-X EDC API to be should be published"
        type: string
      upstream-version:
        required: false
        description: "Version of upstream EDC which is to be used"
        type: string

jobs:
  swagger-api:
    runs-on: ubuntu-latest
    env:
      SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
      SWAGGERHUB_USER: ${{ secrets.SWAGGERHUB_USER }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install Swagger CLI
        run: |
          npm i -g swaggerhub-cli

      - name: Extract versions
        run: |
          if [ -z ${{ inputs.downstream-version }} ]; then
            export DOWNSTREAM_VERSION=$(grep "version" gradle.properties  | awk -F= '{print $2}')
          else
            export DOWNSTREAM_VERSION=${{ inputs.downstream-version }}
          fi
          
          if [ -z ${{ inputs.upstream-version }} ]; then
            export UPSTREAM_VERSION=$(grep "edc = " gradle/libs.versions.toml  | awk -F= '{print $2}' | jq -r)
          else
            export UPSTREAM_VERSION=${{ inputs.upstream-version }}
          fi
          echo "DOWNSTREAM_VERSION=$DOWNSTREAM_VERSION" >> "$GITHUB_ENV"
          echo "UPSTREAM_VERSION=$UPSTREAM_VERSION" >> "$GITHUB_ENV"

      - name: Resolve TX EDC API Spec
        shell: bash
        run: |
          ./gradlew resolve

      - name: Download upstream API specs
        run: |
          curl -X GET https://api.swaggerhub.com/apis/eclipse-edc-bot/management-api/${{ env.UPSTREAM_VERSION }}/swagger.yaml > resources/openapi/yaml/upstream-management-api.yaml
          curl -X GET https://api.swaggerhub.com/apis/eclipse-edc-bot/control-api/${{ env.UPSTREAM_VERSION }}/swagger.yaml > resources/openapi/yaml/upstream-control-api.yaml

      - name: Merge API specs
        run: |
          ./gradlew -PapiTitle="Tractus-X EDC REST API" -PapiDescription="Tractus-X EDC API Documentation" :mergeApiSpec --input=./resources/openapi/yaml --output=./resources/openapi/yaml/tractusx-edc-api.yaml

      # create API, will fail if exists
      - name: Create API
        continue-on-error: true
        run: |
          swaggerhub api:create ${{ env.SWAGGERHUB_USER }}/tractusx-edc/${{ env.DOWNSTREAM_VERSION }} -f ./resources/openapi/yaml/tractusx-edc-api.yaml --visibility=public --published=unpublish

      # Post the API to SwaggerHub as "unpublished", because published APIs cannot be overwritten
      - name: Publish API Specs to SwaggerHub
        run: |
          if [[ ${{ env.DOWNSTREAM_VERSION }} != *-SNAPSHOT ]]; then
            echo "no snapshot, will set the API to 'published'";
            swaggerhub api:update ${{ env.SWAGGERHUB_USER }}/tractusx-edc/${{ env.DOWNSTREAM_VERSION }} -f ./resources/openapi/yaml/tractusx-edc-api.yaml --visibility=public --published=publish
          else
            echo "snapshot, will set the API to 'unpublished'";
            swaggerhub api:update ${{ env.SWAGGERHUB_USER }}/tractusx-edc/${{ env.DOWNSTREAM_VERSION }} -f ./resources/openapi/yaml/tractusx-edc-api.yaml --visibility=public --published=unpublish
          fi
