---
name: "Trivy"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  workflow_run:
    workflows: [ "Build" ]
    branches:
      - main
      - releases
      - release/*
      - hotfix/*
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    types:
      - completed

jobs:
  git-sha7:
    name: Determine short git sha
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.git-sha7.outputs.SHA7 }}
    steps:
      - name: Resolve git 7-chars sha
        id: git-sha7
        run: |
          echo "SHA7=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  trivy-analyze-config:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          # ignore-unfixed: true
          exit-code: "1"
          hide-progress: false
          format: "sarif"
          output: "trivy-results-config.sarif"
          severity: "CRITICAL,HIGH"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: "trivy-results-config.sarif"

  trivy:
    needs: [ git-sha7 ]
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # continue scanning other images although if the other has been vulnerable
      matrix:
        image:
          - edc-runtime-memory
          - edc-controlplane-memory-hashicorp-vault
          - edc-controlplane-postgresql
          - edc-controlplane-postgresql-hashicorp-vault
          - edc-dataplane-azure-vault
          - edc-dataplane-hashicorp-vault
    steps:
      - uses: actions/checkout@v3.3.0

        ## This step will fail if the docker images is not found
      - name: "Check if image exists"
        id: imageCheck
        run: |
          docker manifest inspect tractusx/${{ matrix.image }}:sha-${{ needs.git-sha7.outputs.value }}
        continue-on-error: true

        ## the next two steps will only execute if the image exists check was successful
      - name: Run Trivy vulnerability scanner
        if: success() && steps.imageCheck.outcome != 'failure'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "tractusx/${{ matrix.image }}:sha-${{ needs.git-sha7.outputs.value }}"
          format: "sarif"
          output: "trivy-results-${{ matrix.image }}.sarif"
          exit-code: "1"
          severity: "CRITICAL,HIGH"
          timeout: "10m0s"
      - name: Upload Trivy scan results to GitHub Security tab
        if: success() && steps.imageCheck.outcome != 'failure'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results-${{ matrix.image }}.sarif"
